"""Tests for yield-curve fitting, bootstrapping and PCA.

The bootstrap test is the important one: a bootstrap that does not reprice its
own inputs back to par is silently wrong, and every valuation downstream
inherits the error.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from tqe.curve.bootstrap import (
    discount_to_zero,
    forward_rate,
    interpolate_curve,
    par_to_zero,
    zero_curve_function,
    zero_to_discount,
    zero_to_forward,
)
from tqe.curve.nelson_siegel import (
    DIEBOLD_LI_TAU1,
    NSSParams,
    fit_nss,
    fit_nss_history_fixed,
    nss_zero_rate,
)
from tqe.curve.pca import fit_curve_pca, rolling_pca_factors

TENORS = np.array([0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0, 20.0, 30.0])


def _normal_curve() -> np.ndarray:
    """A plausible upward-sloping curve."""
    return np.array([0.0390, 0.0402, 0.0415, 0.0434, 0.0441, 0.0448, 0.0459, 0.0473, 0.0521, 0.0522])


def _inverted_curve() -> np.ndarray:
    """2023-style inversion - the case naive curve code gets wrong."""
    return np.array([0.0540, 0.0545, 0.0530, 0.0490, 0.0460, 0.0430, 0.0425, 0.0425, 0.0455, 0.0440])


# --------------------------------------------------------------------------- #
# Nelson-Siegel-Svensson
# --------------------------------------------------------------------------- #
class TestNSS:
    def test_zero_rate_finite_at_zero(self):
        """The loading (1-exp(-t/tau))/(t/tau) is 0/0 at t=0 and must be handled."""
        r = nss_zero_rate(np.array([0.0]), 0.045, -0.02, 0.03, -0.015, 1.8, 9.0)
        assert np.isfinite(r).all()

    def test_short_rate_limit(self):
        """As t -> 0 the model's rate approaches beta0 + beta1."""
        p = NSSParams(0.045, -0.02, 0.03, -0.015, 1.8, 9.0)
        assert float(p.zero_rate(1e-10)) == pytest.approx(p.beta0 + p.beta1, abs=1e-6)

    def test_long_rate_limit(self):
        """As t -> infinity all decaying loadings vanish and only beta0 survives."""
        p = NSSParams(0.045, -0.02, 0.03, -0.015, 1.8, 9.0)
        assert float(p.zero_rate(500.0)) == pytest.approx(p.beta0, abs=1e-3)

    def test_fits_a_normal_curve_tightly(self):
        _, rmse = fit_nss(TENORS, _normal_curve())
        assert rmse * 1e4 < 5.0, "NSS should fit a normal curve to under 5bp"

    def test_fits_an_inverted_curve(self):
        """Inversions are where 3-factor models fail; Svensson's 2nd hump handles them."""
        _, rmse = fit_nss(TENORS, _inverted_curve())
        assert rmse * 1e4 < 10.0

    def test_reproduces_its_own_output(self):
        """Fitting a curve generated by the model must recover that curve."""
        true = NSSParams(0.045, -0.02, 0.03, -0.015, 1.8, 9.0)
        y = true.zero_rate(TENORS)
        fit, _ = fit_nss(TENORS, y)
        assert np.abs(fit.zero_rate(TENORS) - y).max() * 1e4 < 1.0

    def test_nelson_siegel_mode_zeroes_beta3(self):
        p, _ = fit_nss(TENORS, _normal_curve(), model="nelson_siegel")
        assert p.beta3 == 0.0

    def test_rejects_too_few_points(self):
        with pytest.raises(ValueError):
            fit_nss(TENORS[:2], _normal_curve()[:2])

    def test_array_roundtrip(self):
        p = NSSParams(0.045, -0.02, 0.03, -0.015, 1.8, 9.0)
        assert NSSParams.from_array(p.as_array()).as_array() == pytest.approx(p.as_array())

    def test_fixed_tau_history_is_stable(self):
        """Fixed decays make the betas identifiable; free decays do not.

        This is the property the whole feature pipeline depends on - see the
        commentary on DIEBOLD_LI_TAU1.
        """
        idx = pd.bdate_range("2020-01-01", periods=300)
        rng = np.random.default_rng(0)
        base = _normal_curve()
        drift = np.cumsum(rng.normal(0, 0.0004, len(idx)))
        curve = pd.DataFrame(
            {c: base[i] + drift for i, c in enumerate(
                ["3 Mo", "6 Mo", "1 Yr", "2 Yr", "3 Yr", "5 Yr", "7 Yr", "10 Yr", "20 Yr", "30 Yr"])},
            index=idx,
        )
        res = fit_nss_history_fixed(curve)
        ok = res.dropna(subset=["beta0"])
        assert len(ok) > 250
        assert (ok["tau1"] == DIEBOLD_LI_TAU1).all()
        # A parallel-shifted curve must move beta0 and leave the shape alone.
        assert ok["beta3"].std() < 0.02


# --------------------------------------------------------------------------- #
# Bootstrapping
# --------------------------------------------------------------------------- #
class TestBootstrap:
    def _reprice(self, tenors, zeros, par_tenors, par_yields) -> float:
        """Max |price - 100| when repricing the input par bonds off the zeros."""
        fn = zero_curve_function(tenors, zeros)
        worst = 0.0
        for ti, yi in zip(par_tenors, par_yields):
            n = int(np.floor(ti * 2 + 1e-9))
            if n <= 1:
                continue
            times = ti - 0.5 * np.arange(n - 1, -1, -1)
            times = times[times > 0]
            cf = np.full(len(times), yi / 2 * 100)
            cf[-1] += 100
            dfs = np.array([(1 + fn(float(x)) / 2) ** (-2 * x) for x in times])
            worst = max(worst, abs(float((cf * dfs).sum()) - 100.0))
        return worst

    def test_round_trip_normal_curve(self):
        """THE bootstrap test: input par bonds must reprice to exactly 100."""
        y = _normal_curve()
        t, z = par_to_zero(TENORS, y)
        assert self._reprice(t, z, TENORS, y) < 1e-8

    def test_round_trip_inverted_curve(self):
        y = _inverted_curve()
        t, z = par_to_zero(TENORS, y)
        assert self._reprice(t, z, TENORS, y) < 1e-8

    def test_round_trip_flat_curve(self):
        """On a flat curve the zero curve equals the par curve."""
        y = np.full(len(TENORS), 0.04)
        t, z = par_to_zero(TENORS, y)
        assert np.abs(z - 0.04).max() < 1e-8

    def test_zero_above_par_on_upward_curve(self):
        """A rising par curve implies zeros above par at the long end."""
        y = _normal_curve()
        t, z = par_to_zero(TENORS, y)
        long = t >= 5.0
        assert (z[long] > np.interp(t[long], TENORS, y)).all()

    def test_short_tenors_pass_through(self):
        """Under one coupon period there is nothing to bootstrap."""
        t, z = par_to_zero(TENORS, _normal_curve())
        assert z[0] == pytest.approx(_normal_curve()[0])

    def test_discount_zero_roundtrip(self):
        z = np.array([0.03, 0.04, 0.045])
        t = np.array([1.0, 5.0, 10.0])
        assert discount_to_zero(t, zero_to_discount(t, z)) == pytest.approx(z, abs=1e-12)

    def test_forwards_positive_on_normal_curve(self):
        t, z = par_to_zero(TENORS, _normal_curve())
        assert (zero_to_forward(t, z) > 0).all()

    def test_forward_rate_consistency(self):
        """Compounding the 1y spot into the 1y-2y forward must give the 2y spot."""
        fn = zero_curve_function(np.array([1.0, 2.0]), np.array([0.04, 0.045]))
        f = forward_rate(fn, 1.0, 2.0)
        implied = ((1 + 0.04 / 2) ** 2 * (1 + f / 2) ** 2) ** (1 / 4) * 2 - 2
        assert implied == pytest.approx(0.045, abs=1e-9)

    def test_handles_nan_input(self):
        y = _normal_curve().copy()
        y[3] = np.nan
        t, z = par_to_zero(TENORS, y)
        assert len(t) == len(TENORS) - 1
        assert np.isfinite(z).all()

    def test_empty_input(self):
        t, z = par_to_zero(np.array([]), np.array([]))
        assert len(t) == 0 and len(z) == 0

    @pytest.mark.parametrize("method", ["linear", "log_linear_df", "cubic", "monotone_cubic"])
    def test_interpolation_hits_the_nodes(self, method):
        t = np.array([1.0, 5.0, 10.0])
        v = np.array([0.03, 0.042, 0.047])
        assert interpolate_curve(t, v, t, method=method) == pytest.approx(v, abs=1e-8)

    def test_interpolation_extrapolates_flat(self):
        t = np.array([1.0, 5.0, 10.0])
        v = np.array([0.03, 0.042, 0.047])
        out = interpolate_curve(t, v, np.array([0.1, 50.0]))
        assert out[0] == pytest.approx(0.03)
        assert out[1] == pytest.approx(0.047)

    def test_unknown_method_rejected(self):
        with pytest.raises(ValueError):
            interpolate_curve(np.array([1.0, 2.0]), np.array([0.03, 0.04]),
                              np.array([1.5]), method="quantum")


# --------------------------------------------------------------------------- #
# PCA
# --------------------------------------------------------------------------- #
class TestPCA:
    @staticmethod
    def _synthetic_changes(n: int = 900) -> pd.DataFrame:
        """Curve changes built from a known 3-factor structure plus noise."""
        rng = np.random.default_rng(7)
        cols = ["3 Mo", "1 Yr", "2 Yr", "5 Yr", "10 Yr", "30 Yr"]
        years = np.array([0.25, 1, 2, 5, 10, 30])
        level = rng.normal(0, 0.0040, n)
        slope = rng.normal(0, 0.0015, n)
        curv = rng.normal(0, 0.0006, n)
        l_load = np.ones(6)
        s_load = (years - years.mean()) / years.std()
        c_load = -((years - 5.0) ** 2) / 100.0
        data = (np.outer(level, l_load) + np.outer(slope, s_load) + np.outer(curv, c_load)
                + rng.normal(0, 0.0002, (n, 6)))
        return pd.DataFrame(data, columns=cols, index=pd.bdate_range("2015-01-01", periods=n))

    def test_three_factors_explain_almost_everything(self):
        p = fit_curve_pca(self._synthetic_changes(), 3)
        assert p.explained_variance_ratio_.sum() > 0.95

    def test_variance_ratios_are_descending(self):
        p = fit_curve_pca(self._synthetic_changes(), 3)
        r = p.explained_variance_ratio_
        assert r[0] > r[1] > r[2]

    def test_pc1_loads_positively_everywhere(self):
        """Sign convention: a positive level score must mean a sell-off."""
        p = fit_curve_pca(self._synthetic_changes(), 3)
        assert (p.components_[0] > 0).all()

    def test_pc2_is_monotone_in_maturity(self):
        """Slope loadings must increase with maturity.

        Tested with Spearman rather than Pearson: the loading is monotone in
        maturity but not *linear* in tenor rank, because the tenor grid itself
        is geometric (0.25y .. 30y). Pearson against rank measures the wrong
        property and reads ~0.77 for a perfectly monotone loading.
        """
        from scipy import stats

        p = fit_curve_pca(self._synthetic_changes(), 3)
        rho = stats.spearmanr(np.arange(len(p.tenors)), p.components_[1]).statistic
        assert rho > 0.9

    def test_pc3_is_a_hump(self):
        """Curvature must move the belly against the wings."""
        p = fit_curve_pca(self._synthetic_changes(), 3)
        v = p.components_[2]
        n = len(v)
        lo, hi = n // 3, 2 * n // 3
        belly = v[lo:hi].mean()
        wings = np.concatenate([v[:lo], v[hi:]]).mean()
        assert np.sign(belly) != np.sign(wings)

    def test_components_are_orthonormal(self):
        p = fit_curve_pca(self._synthetic_changes(), 3)
        gram = p.components_ @ p.components_.T
        assert np.allclose(gram, np.eye(3), atol=1e-8)

    def test_transform_inverse_transform_roundtrip(self):
        ch = self._synthetic_changes()
        p = fit_curve_pca(ch, 6)  # full rank
        assert p.inverse_transform(p.transform(ch)) == pytest.approx(ch.to_numpy(), abs=1e-8)

    def test_factor_frame_is_named(self):
        ch = self._synthetic_changes()
        f = fit_curve_pca(ch, 3).factor_frame(ch)
        assert list(f.columns) == ["level", "slope", "curvature"]

    def test_rolling_factors_are_causal(self):
        """The decisive leakage test.

        Corrupt the tail of the sample and confirm that scores computed before
        the corruption are byte-identical. If loadings leaked from the future,
        changing the future would change the past.
        """
        ch = self._synthetic_changes()
        cut = 600
        base = rolling_pca_factors(ch, window=252, n_factors=3, refit_every=21)

        tampered = ch.copy()
        tampered.iloc[cut:] *= 25.0          # violently change the future only
        after = rolling_pca_factors(tampered, window=252, n_factors=3, refit_every=21)

        a = base.iloc[:cut].dropna()
        b = after.iloc[:cut].dropna()
        assert len(a) > 100
        assert np.allclose(a.to_numpy(), b.loc[a.index].to_numpy(), atol=1e-12)

    def test_rolling_factors_warm_up_is_nan(self):
        ch = self._synthetic_changes()
        f = rolling_pca_factors(ch, window=252, n_factors=3)
        assert f.iloc[:252].isna().all().all()

    def test_rejects_empty_input(self):
        with pytest.raises(ValueError):
            fit_curve_pca(pd.DataFrame({"a": [np.nan, np.nan]}), 1)
